### ISSUE TITLE
Random error in testing environment

### ISSUE THREAD

**Issue by michael-rubel** [keepsuit/laravel-temporal#7]
Hi @cappuc!

Tests are randomly failing with the following error:
```
Error 'rpc: can't find service kv.Clear' on tcp://127.0.0.1:6001
```

Tried to bootstrap the server/workers after each test, but it didn't help.
Do you have any idea why this happen?

I have a fresh Laravel 10 & Sail dev environment with an additional GRPC extension installed.

**Comment by cappuc** [comment]
Hi @michael-rubel!

I'm not very familiar with sail but the error should be caused by `Keepsuit\LaravelTemporal\Testing\TemporalMocker` when mocking an activity/workflow and it cant connect to the roadrunner instance that run the temporal worker.

Are you using the `Keepsuit\LaravelTemporal\Testing\WithTemporal` trait in you test? 
The trait will start the temporal server and a worker. If you are running the temporal server separately, you can set `TEMPORAL_TESTING_SERVER=false` env variable and it will only start the worker.

**Comment by michael-rubel** [comment]
@cappuc Yeah, I'm using the `WithTemporal` trait. Even tried to enable the debug in the testing environment class, and it seems it starts okay (says `done` on both server and worker) but still randomly fails at this point.

**Comment by cappuc** [comment]
@michael-rubel Can you try with the main branch?
I changed a bit the retry logic for the communication with the test worker and the checks for the worker process stopping

**Comment by michael-rubel** [comment]
@cappuc Looks like it works as expected on the main branch. Thank you for the quick fix!

**Comment by cappuc** [comment]
@michael-rubel I've tagged [v0.6.0](https://github.com/keepsuit/laravel-temporal/releases/tag/v0.6.0) release with this fix.
